In [39]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import root_mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet

In [40]:
# We will load the diabetes dataset , train test split it and then check the r2 score and rmse 
# for Linear , Ridge , Lasso and Elastic net .

In [41]:
X , y = load_diabetes(return_X_y=True) # Load Diabetes dataset

In [42]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42) # Split into training set and testing set 

In [43]:
# Applying Linear Regression on the training set 
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)

In [44]:
lr.coef_,lr.intercept_

(array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
        -931.48884588,  518.06227698,  163.41998299,  275.31790158,
         736.1988589 ,   48.67065743]),
 np.float64(151.34560453985995))

In [45]:
r2_score(y_test,y_pred_lr),root_mean_squared_error(y_test,y_pred_lr)

(0.4526027629719197, 53.853445836765914)

In [46]:
# Applying Ridge Regression on the training set 
rdg = Ridge(alpha=0.1)
rdg.fit(X_train,y_train)
y_pred_rdg = rdg.predict(X_test)


In [ ]:
rdg.coef_,rdg.intercept_

(array([  42.85566976, -205.49431899,  505.08903304,  317.0932049 ,
        -108.50026183,  -86.23673333, -190.36318008,  151.70708637,
         392.28931896,   79.9081772 ]),
 np.float64(151.45857456679613))

In [48]:
r2_score(y_test,y_pred_rdg),root_mean_squared_error(y_test,y_pred_rdg)

(0.46085219464119254, 53.446111997699646)

In [49]:
# Applying Lassos\ Regression on the training set 
las = Lasso(alpha=0.01)
las.fit(X_train,y_train)
y_pred_las = las.predict(X_test)

In [ ]:
las.coef_,las.intercept_

(array([  35.34745133, -231.90666401,  551.3032416 ,  341.31346895,
        -483.56713972,  165.99053164,  -25.8348991 ,  216.87580276,
         566.81500336,   49.70247477]),
 np.float64(151.3434891207199))

In [51]:
r2_score(y_test,y_pred_las),root_mean_squared_error(y_test,y_pred_las)

(0.45668611945806237, 53.65220765436038)

In [52]:
# Applying Elastic Regression on the training set 
# Here in Elastic Regression we can control the l1.ratio and correspondingly the ratio of l2 will be set ,
#  so we can contral the amount of L1 and L2 be applied in ElasticNet .
# Also of course alpha is the lambda value.
els = ElasticNet(alpha=0.001,l1_ratio=0.9)
els.fit(X_train,y_train)
y_pred_els = els.predict(X_test)


In [ ]:
els.coef_,els.intercept_

(array([  41.46801473, -226.35657357,  536.02388748,  333.27992922,
        -206.10683985,  -32.82500911, -157.61006775,  167.8957042 ,
         448.05753014,   64.27751646]),
 np.float64(151.36849515152187))

In [54]:
r2_score(y_test,y_pred_els),root_mean_squared_error(y_test,y_pred_els)

(0.45837006414135006, 53.56899841996713)

In [62]:
# Comparing values of coef and intercept from all the models.
print(f"Linear Regression \n Coeffecients : {lr.coef_} \n Intercept : {lr.intercept_}")
print(f"Ridge Regression \n Coeffecients : {rdg.coef_} \n Intercept : {rdg.intercept_}")
print(f"Lasso Regression \n Coeffecients : {las.coef_} \n Intercept : {las.intercept_}")
print(f"ElasticNet Regression \n Coeffecients : {els.coef_} \n Intercept : {els.intercept_}")

Linear Regression 
 Coeffecients : [  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588
  518.06227698  163.41998299  275.31790158  736.1988589    48.67065743] 
 Intercept : 151.34560453985995
Ridge Regression 
 Coeffecients : [  42.85566976 -205.49431899  505.08903304  317.0932049  -108.50026183
  -86.23673333 -190.36318008  151.70708637  392.28931896   79.9081772 ] 
 Intercept : 151.45857456679613
Lasso Regression 
 Coeffecients : [  35.34745133 -231.90666401  551.3032416   341.31346895 -483.56713972
  165.99053164  -25.8348991   216.87580276  566.81500336   49.70247477] 
 Intercept : 151.3434891207199
ElasticNet Regression 
 Coeffecients : [  41.46801473 -226.35657357  536.02388748  333.27992922 -206.10683985
  -32.82500911 -157.61006775  167.8957042   448.05753014   64.27751646] 
 Intercept : 151.36849515152187


In [63]:
# Comparing values of r2score across all the models.
print(f"Linear Regression \n r2Score : {r2_score(y_test,y_pred_lr)} ")
print(f"Ridge Regression \n r2Score  : {r2_score(y_test,y_pred_rdg)}")
print(f"Lasso Regression \n r2Score : {r2_score(y_test,y_pred_las)}")
print(f"ElasticNet Regression \n r2Score  : {r2_score(y_test,y_pred_els)}")

Linear Regression 
 r2Score : 0.4526027629719197 
Ridge Regression 
 r2Score  : 0.46085219464119254
Lasso Regression 
 r2Score : 0.45668611945806237
ElasticNet Regression 
 r2Score  : 0.45837006414135006


In [64]:
# Comparing values of rmse across all the models.
print(f"Linear Regression \n rmse : {root_mean_squared_error(y_test,y_pred_lr)} ")
print(f"Ridge Regression \n rmse  : {root_mean_squared_error(y_test,y_pred_rdg)}")
print(f"Lasso Regression \n rmse : {root_mean_squared_error(y_test,y_pred_las)}")
print(f"ElasticNet Regression \n rmse  : {root_mean_squared_error(y_test,y_pred_els)}")

Linear Regression 
 rmse : 53.853445836765914 
Ridge Regression 
 rmse  : 53.446111997699646
Lasso Regression 
 rmse : 53.65220765436038
ElasticNet Regression 
 rmse  : 53.56899841996713
