In [1]:
import numpy as np
import random
from sklearn.neighbors import NearestNeighbors

In [2]:
X = np.ceil(np.random.rand(10,2)*10)

In [3]:
X

array([[ 8.,  1.],
       [ 1.,  1.],
       [ 5.,  3.],
       [ 7., 10.],
       [ 7., 10.],
       [ 3.,  5.],
       [ 3.,  6.],
       [ 1.,  8.],
       [ 2.,  4.],
       [ 6.,  1.]])

In [4]:
nnbrs = NearestNeighbors(
    n_neighbors = 3,
    algorithm = 'ball_tree'
).fit(X)

In [5]:
distances,indices = nnbrs.kneighbors(X)

In [6]:
indices

array([[0, 9, 2],
       [1, 8, 2],
       [2, 9, 5],
       [3, 4, 6],
       [3, 4, 6],
       [5, 6, 8],
       [6, 5, 8],
       [7, 6, 5],
       [8, 5, 6],
       [9, 0, 2]])

In [7]:
distances

array([[0.        , 2.        , 3.60555128],
       [0.        , 3.16227766, 4.47213595],
       [0.        , 2.23606798, 2.82842712],
       [0.        , 0.        , 5.65685425],
       [0.        , 0.        , 5.65685425],
       [0.        , 1.        , 1.41421356],
       [0.        , 1.        , 2.23606798],
       [0.        , 2.82842712, 3.60555128],
       [0.        , 1.41421356, 2.23606798],
       [0.        , 2.        , 2.23606798]])

In [8]:
nnbrs.kneighbors_graph(X).toarray()

array([[1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
min_distances = np.sort(distances[:,1:],axis=0)

In [15]:
min_distances

array([[0.        , 1.41421356],
       [0.        , 2.23606798],
       [1.        , 2.23606798],
       [1.        , 2.23606798],
       [1.41421356, 2.82842712],
       [2.        , 3.60555128],
       [2.        , 3.60555128],
       [2.23606798, 4.47213595],
       [2.82842712, 5.65685425],
       [3.16227766, 5.65685425]])