In [2]:
# Import required libraries 
import numpy as np
import random
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

In [3]:
# This is a numpy function I made for this notebook.
# Basically It will take a random float values between 0 to 1 of size passed.
# Then all the values inside the newly formed array is multplied by 10 and converted to range (1-10) .
# Then we take the ceiling value of this so that it truly is in the range (1-10).
X = np.ceil(np.random.rand(10,2)*10)

In [4]:
X # Look of the new numpy array

array([[8., 3.],
       [3., 6.],
       [2., 8.],
       [7., 1.],
       [2., 3.],
       [8., 7.],
       [6., 3.],
       [6., 1.],
       [9., 2.],
       [2., 7.]])

In [ ]:
# NearestNeighbors basically calcualates the distance for each of the point with other points using the algorithm passed
# and then returns the indices and distances from the Nearest Neighbors (the value is sey by us) from that point 
# (done for each point in the graph).

# Instantiate the model
nnbrs = NearestNeighbors(
    n_neighbors = 3, # The number of neighbors each point should have 
    algorithm = 'ball_tree' # The algorithm used to compute Nearest Neighbors
).fit(X) # Also fitting X during instantiation

In [6]:
distances,indices = nnbrs.kneighbors(X) # Use the kneighbors method and pass the matrix for which we are calculating the nearestneighbors.
# The distances and indices for the nearest k neighbors will be returned

In [7]:
indices # The indices of the nearest neighbor for each point

array([[0, 8, 6],
       [1, 9, 2],
       [2, 9, 1],
       [3, 7, 0],
       [4, 1, 6],
       [5, 0, 6],
       [6, 7, 0],
       [7, 3, 6],
       [8, 0, 3],
       [9, 2, 1]])

In [ ]:
distances # The distance between each nearest neighbor sorted and limited according to the no of neighbors passed
# The 0 is the distance of the point with itself
# So technically it is considering itself as a point also for nearest neighbors.

array([[0.        , 1.41421356, 2.        ],
       [0.        , 1.41421356, 2.23606798],
       [0.        , 1.        , 2.23606798],
       [0.        , 1.        , 2.23606798],
       [0.        , 3.16227766, 4.        ],
       [0.        , 4.        , 4.47213595],
       [0.        , 2.        , 2.        ],
       [0.        , 1.        , 2.        ],
       [0.        , 1.41421356, 2.23606798],
       [0.        , 1.        , 1.41421356]])

In [9]:
nnbrs.kneighbors_graph(X).toarray() # This is the matrix of the points and their respective nearest neighbors.

array([[1., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 1.]])