In [56]:
# Import required libraries 
import numpy as np
import random
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

In [57]:
# This is a numpy function I made for this notebook.
# Basically It will take a random float values between 0 to 1 of size passed.
# Then all the values inside the newly formed array is multplied by 10 and converted to range (1-10) .
# Then we take the ceiling value of this so that it truly is in the range (1-10).
X = np.ceil(np.random.rand(10,2)*10)

In [58]:
X # Look of the new numpy array

array([[ 5.,  6.],
       [ 6.,  8.],
       [ 6.,  5.],
       [ 7., 10.],
       [ 8., 10.],
       [10.,  3.],
       [ 4.,  9.],
       [ 3.,  4.],
       [ 4.,  8.],
       [ 8.,  9.]])

In [59]:
# NearestNeighbors basically calcualtes the distance for each of the point with other points using the algorithm passed
# and then returns the indices and distances from the Nearest Neighbors (the value is sey by us) from that point 
# (done for each point in the graph).

# Instantiate the model
nnbrs = NearestNeighbors(
    n_neighbors = 3, # The number of neighbors each point should have 
    algorithm = 'ball_tree' # The algorithm used to compute Nearest Neighbors
).fit(X) # Also fitting X during instantiation

In [60]:
distances,indices = nnbrs.kneighbors(X) # Use the kneighbors method and pass the matrix for which we are calculating the nearestneighbors.
# The distances and indices for the nearest k neighbors will be returned

In [61]:
indices # The indices of the nearest neighbor for each point

array([[0, 2, 1],
       [1, 8, 0],
       [2, 0, 1],
       [3, 4, 9],
       [4, 9, 3],
       [5, 2, 0],
       [6, 8, 1],
       [7, 0, 2],
       [8, 6, 1],
       [9, 4, 3]])

In [62]:
distances # The distance between each nearest neighbor
# The 0 is the distance of the point with itself
# So technically it is considering itself as a point also for nearest neighbors.

array([[0.        , 1.41421356, 2.23606798],
       [0.        , 2.        , 2.23606798],
       [0.        , 1.41421356, 3.        ],
       [0.        , 1.        , 1.41421356],
       [0.        , 1.        , 1.        ],
       [0.        , 4.47213595, 5.83095189],
       [0.        , 1.        , 2.23606798],
       [0.        , 2.82842712, 3.16227766],
       [0.        , 1.        , 2.        ],
       [0.        , 1.        , 1.41421356]])

In [63]:
nnbrs.kneighbors_graph(X).toarray() # This is the matrix of the points and their respective nearest neighbors.

array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 1.]])

In [ ]:
# We use Argsort to keep a track of the indices while sorting the row.
# Argsort will return the indices which were reordered when we sort the distances.
min_distances_indices = (np.argsort(distances[:,1],axis=0))

# NOTE : WORK still in progress

In [86]:
min_distances_indices # These are the indices of the sorted values 

array([3, 4, 6, 8, 9, 0, 2, 1, 7, 5])

In [87]:
distances[min_distances_indices] # Sorted distances

array([[0.        , 1.        , 1.41421356],
       [0.        , 1.        , 1.        ],
       [0.        , 1.        , 2.23606798],
       [0.        , 1.        , 2.        ],
       [0.        , 1.        , 1.41421356],
       [0.        , 1.41421356, 2.23606798],
       [0.        , 1.41421356, 3.        ],
       [0.        , 2.        , 2.23606798],
       [0.        , 2.82842712, 3.16227766],
       [0.        , 4.47213595, 5.83095189]])